### ISSUE TITLE
手机标题&版权字体

### ISSUE THREAD

**Issue by movny** [Litreily/hexo-theme-snark#6]
手机界面的标题不是居中，左边有菜单的icon，导致标题偏右，看起来很不舒服
版权声明前面四个字是黄色的，和前面紫色线条 后面蓝色链接 搭配起来过于明亮，感觉白色灰色就可以

**Comment by movny** [comment]
性能很好

**Comment by movny** [comment]
图片有fancybox的适配，但视频没有什么支持，照片视频一起引用的时候不规整，建议增加video.js或dplayer

**Comment by Litreily** [comment]
> 手机界面的标题不是居中，左边有菜单的icon，导致标题偏右，看起来很不舒服
> 版权声明前面四个字是黄色的，和前面紫色线条 后面蓝色链接 搭配起来过于明亮，感觉白色灰色就可以

嗯，手机上看起来应该没啥问题吧，我看着还好，至于黄色声明，这个确实可能亮眼些，可以帮忙修改下吗？我觉得白色OK
