### ISSUE TITLE
Archives 页面无法加载

### ISSUE THREAD

**Issue by T-Mux** [Litreily/hexo-theme-snark#9]
执行 <code>hexo s</code> 进行预览

在点击“归档”页面后，终端给出以下报错：

````Shell Script
Unhandled rejection TypeError: /Users/tmux/Documents/Blog/themes/snark/layout/archive.pug:19
    17| 
    18|         //Use lodash to classify posts. See https://lodash.com/docs#groupBy
  > 19|         each posts, year in _.groupBy(page.posts.toArray(), function(p){return -p.date.format('YYYY')})
    20|             h2= -year
    21|             ul.list
    22|                 for post in posts

Cannot read property 'groupBy' of undefined
    at eval (eval at wrap (/Users/tmux/Documents/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:442:17)
    at eval (eval at wrap (/Users/tmux/Documents/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:546:4)
    at template (eval at wrap (/Users/tmux/Documents/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:667:72)
    at _View._compiled (/Users/tmux/Documents/Blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/tmux/Documents/Blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/tmux/Documents/Blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/tmux/Documents/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/tmux/Documents/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/tmux/Documents/Blog/node_modules/hexo/lib/hexo/router.js:30:5)
    at RouteStream.Readable.read (_stream_readable.js:475:10)
    at resume_ (_stream_readable.js:962:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by Litreily** [comment]
请确认是否已经创建了`archives`目录和`index.md`，创建方法参考：
https://github.com/Litreily/hexo-theme-snark#add-general-pages

并确保博客目录`_posts`不为空

**Comment by T-Mux** [comment]
是的，我已创建<code>archives</code>目录，是用<code>hexo  new page "archives"</code>进行的创建

这是我的<code>source</code>文件夹目录:

<img width="770" alt="WX20200811-205049@2x" src="https://user-images.githubusercontent.com/33898918/89899515-01275400-dc15-11ea-8bce-729f92090649.png">

这是<code>archives</code>文件夹下的<code>index.md</code>内容：

<img width="1220" alt="WX20200811-205802@2x" src="https://user-images.githubusercontent.com/33898918/89899891-8448aa00-dc15-11ea-8e12-1a7e3acb9ddd.png">

对比您在<code>README</code>文件中提供的<code>source</code>树，发现缺少了<code>source</code>目录下的一个 <code>index.md</code>文件

<img width="472" alt="WX20200811-205126@2x" src="https://user-images.githubusercontent.com/33898918/89900079-d689cb00-dc15-11ea-9a47-d513bd8f5fc6.png">

于是尝试用<code>README</code>文件中提供的代码进行二次覆盖，终端报错

<img width="1625" alt="WX20200811-205147@2x" src="https://user-images.githubusercontent.com/33898918/89900195-fc16d480-dc15-11ea-8da5-1bf45599fd2a.png">

非常头疼，找不到问题出在哪里。是少了<code>source</code>目录下的那个<code>index.md</code>文件造成的吗？

**Comment by Litreily** [comment]
你说的**终端报错**是没有关系的，因为你已经存在对应文件夹了，所以实际上也没有替换。source 目录的`index.md`对应的就是你的主页，如果你主页能正常显示说明是可有可无的，不过你可以手动添加，输入
```
---
layout: page
title: home
---
```

**Comment by Litreily** [comment]
找到问题了，是`hexo 5.0.0`之后不再支持`lodash`了，

https://hexo.io/docs/variables#Global-Variables
> Lodash has been removed from global variables since Hexo 5.0.0. You-Dont-Need-Lodash-Underscore might be helpful for your migration.

你的hexo应该是5.0.0之后的，我会尽快fix，感谢你的report.

**Comment by T-Mux** [comment]
非常感谢作者这么上心，期待更新

**Comment by Litreily** [comment]
@T-Mux 已经fix了，请pull到最新然后再尝试下~

**Comment by T-Mux** [comment]
> @T-Mux 已经fix了，请pull到最新然后再尝试下~

非常感谢，已经解决！我将<code>close</code>这个<code>issue</code>
